default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: reformat
        name: poetry reformat
        entry: poetry run reformat
        language: system
        pass_filenames: false
        types: [python]

      - id: test
        name: poetry test
        entry: poetry run test
        language: system
        pass_filenames: false
        types: [python]
